In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [15]:

x=np.ones((4,8)) # ones array 2D ^_^
print(x)        # print array ^_^

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


## Q#2: Create y array with elements equal to 0.

In [16]:

y=np.zeros((4,8))# zeros array 2D  ^_^
print(y)        # print array ^_^

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


## Q#3: Add x and y arrays.

In [17]:
x+y # ADD 2 array 2D  ^_^

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [21]:
print(x.size )  # the array element numbers ^_^
print(x.ndim)   # 2 dimintion Array ^_^
print(x.shape)  # the Array (rows,colums ) ^_^
print(type(x))  # the general object type for numpy ^_^
print(x.dtype)  # the type for array elements ^_^

32
2
(4, 8)
<class 'numpy.ndarray'>
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [30]:
# write your code here ^_^
w=np.array([[11,12],[13,14],[15,16]]) # the basic method ^_^
print('THE FIRST METHOD :')
print(w)

print('\n'+'\n')

w=np.arange(11,17) # the second method ^_^
w=w.reshape(3,2)
print('THE SECOND METHOD :')
print (w)

THE FIRST METHOD :
[[11 12]
 [13 14]
 [15 16]]



THE SECOND METHOD :
[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [34]:
z=np.arange(1,4)# the z  array ^_^
z=z.reshape(3,1)# reshape the array z to use it with w array ^_^
print(z)

[[1]
 [2]
 [3]]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [38]:
newArray=np.hstack((z,w))# comine z and w arrays in horizontal way ^_^
print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [40]:
for i in range (0,3):
    for j in range(0,3):
        print(newArray[i][j]) # using nasted loop to print all the array elements ^_^

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [41]:

newArray.T  # transpose the array ^_^

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [44]:
# write your code here ^_^
newArray-1 # Decrement the array ^_^

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [48]:

print(newArray.min())# the smallest element
print(newArray.max())# the biggest element

1
16


## Q#12: Print the first row of "newArray" using indexing.

In [52]:
newArray[0,] # the first row

array([ 1, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [53]:
newArray[0,2] # the specific element

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [55]:
newArray[1,1] # the specific element

13

## Q#15: Change the shape of "newArray" to (9,1).

In [56]:

newArray.reshape(9,1) # reshape the array

array([[ 1],
       [11],
       [12],
       [ 2],
       [13],
       [14],
       [ 3],
       [15],
       [16]])

## Q#16: Change the shape of "newArray" to (3,2).

In [59]:
newArray[0:2,].reshape(3,2) #slice the newArray to  reshape the array

array([[ 1, 11],
       [12,  2],
       [13, 14]])

# Well Done 🎉