# Q1: Import numpy library

In [6]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [7]:

np.linspace(0,15.0,15) # generate 15 sequence element

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [36]:
arr1=np.array([1.1,2.1,3.1])  
arr2=np.array([4.1,5.1,6.1])
arr3=np.array([7.1,8.1,9.1])
arr4=np.array([10.1,11.1,12.1])
array3d=np.vstack((arr1,arr2)) # step 1 vstack tow array
array3d=np.vstack((array3d,arr3))# step 2 vstack for the third one
array3d=np.vstack((array3d,arr4))# step 3 vstack for the fourth array
array3d=array3d.reshape(2,2,3)
print(array3d)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [37]:
print (type(array3d))# the array type
print(array3d.dtype)# the element type
print(array3d.shape)# (rows,column)
print(array3d.size) # the element number
print(array3d.ndim )# the dimintion type

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [38]:
array4d=np.expand_dims(array3d , axis=1)
print(array4d)
print(array4d.ndim)

[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]]


 [[[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]
4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [39]:
new_array=array4d.astype(int) # convert the type to int
print(new_array) # print the new array

[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [12]:
# 
for i in range(2):
    for j in range(3):
        for k in range (2):
            print(new_array[i][j][k])
# use 3 for loop because 3D array

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [53]:
new_array[1,0,0,1]  # slice 3d array

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [46]:
new_array[0,0,1,1:]  # slice 3d array

array([5, 6])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [43]:
np.where(new_array == 8) # the path of element 8 


(array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [58]:
new_array.reshape(2,1,3,2) # reshape

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]]],


       [[[ 7,  8],
         [ 9, 10],
         [11, 12]]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [60]:

arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
arr3= np.vstack((arr1,arr2)) # join vertical stack
print(arr3)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [61]:
np.stack((arr1,arr2),axis=1) # join  stack with axis=1

array([[['A', 'B'],
        ['C', 'D']],

       [['E', 'F'],
        ['G', 'H']]], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [62]:
[array1,array2]= np.split(arr3,2,axis=1 )# split into 2 arrays axis=1
print(array1)
print('\n')
print(array2)

[['A']
 ['E']
 ['C']
 ['G']]


[['B']
 ['F']
 ['D']
 ['H']]
